### PR TITLE
Nixify polkadot-launch

### PR DESCRIPTION
**Pull request by bkchr**
Disclaimer: I don't have any idea of javascript/nodejs or whatever.

I finally wanted to use `polkadaot-launch`, so I nixified it. Not sure if you want it :shrug: 

See [here](https://github.com/bkchr/nixos-config/blob/8bb0bcb63c77eb71e73ef2bce0e6be6046e9315d/home/files/projects/parity/shell.nix#L5-L10) for how to use it.

I'm totally fine to remove the nix files if you say that you don't want to have them in the repo. However I was to dumb to make this babel stuff working (main problem is that I have no fucking clue how all this javascript stuff is working :sweat:), so it would be nice if we at least could merge this.

### CODE REVIEW

**Comment by pepyakin** [comment]
Nice.

But I am not clear on one thing: did you try to run it as a mere mortal? I mean running it as the following instead of installing as a nix package:

```
npm run start <your config>
```

Fwiw, here is my `shell.nix`: only node and yarn are required and you can ignore the darwin crap there obviously.  I think I am not going to use the nixified version just because I foresee me tinkering with it.

```
let
  nixpkgs = import <nixpkgs> {};
in
with nixpkgs; pkgs.mkShell {
  buildInputs = [
    darwin.apple_sdk.frameworks.CoreServices
    nodejs-12_x
    yarn
  ];
```

**Comment by bkchr** [comment]
I did not yet run the "pure" version. However I also like to have my stuff reproducible :P Meaning, I want to have the same setup on my laptop/tower. Maybe at some point I want to have some new feature and than I will need to change some stuff, however most of the time I will probably rely on the package in my env. 

I think this is mainly what you like the most personally. At the beginning for example I also had stuff like cargo-remote installed via cargo, but now I also switched that over to a nix package.

**Comment by pepyakin** [comment]
No, I understand and share this, but I am wondering because I suspect that most of the users don't use Nix and I am just interested that it still works for these people

**Comment by bkchr** [comment]
Yeah, but besides removing babel, I did not change anything for other users? 

Or do you just want to make me ensure this? If yes, I can try it your way later as well!

**Comment by shawntabrizi** [comment]
@bkchr what is wrong with `yarn && yarn start config.json`?

**Comment by bkchr** [comment]
Nothing is wrong with that, but I like my packages bundled as explained above :D 

As said, I can remove this nix stuff and maintain on my own. Would just be nice to get rid off babel.

**Review by shawntabrizi — APPROVED** [review]

**Comment by pepyakin** [comment]
Tried locally, and I get the following:

```
yarn && yarn start                                                                                                                                                                                                             ~/dev/parity/polkadot-launch
yarn install v1.22.5
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.12s.
yarn run v1.22.5
$ node src/index.js
(node:22364) ExperimentalWarning: The ESM module loader is experimental.
file:///Users/pepyakin/dev/parity/polkadot-launch/src/rpc.js:2
import { Keyring } from '@polkadot/api';
         ^^^^^^^
SyntaxError: The requested module '@polkadot/api' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from '@polkadot/api';
const { Keyring } = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:97:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:143:20)
    at async Loader.import (internal/modules/esm/loader.js:182:24)
    at async Object.loadESM (internal/process/esm_loader.js:84:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

that's node v12.19.0

**Comment by pepyakin** [comment]
I've taken a shot at fixing this and I found out that it should be pretty simple to keep babel and just workaround the whole issue. 
PTAL #24

**Comment by bkchr** [comment]
Nice!

**Pull request closed without merging**
